import React, { useState, useEffect } from 'react';
import { Application, LoanDocument, ValidationResult } from '../../types';
import { useApp } from '../../context/AppContext';
import { generateOperationsSummary } from '../../utils/summaryGenerator';
import { Save, RotateCcw, Check, User, Clock, FileText } from 'lucide-react';
import { formatDateTime } from '../../utils/formatters';

interface Props {
  application: Application;
  documents: LoanDocument[];
  validation: ValidationResult;
}

export const OperationsSummary: React.FC<Props> = ({ application, documents, validation }) => {
  const { saveOperationsSummary, resetOperationsSummary, currentUser } = useApp();
  const isReadOnly = currentUser.role === 'Auditor';

  // Base generated summary
  const autoGenerated = generateOperationsSummary(application, documents, validation);

  // Current text in editor
  const [content, setContent] = useState<string>(application.editedSummary || autoGenerated);
  const [isSavedFeedback, setIsSavedFeedback] = useState(false);

  // Sync if application changes or autoGenerated changes when not custom-edited
  useEffect(() => {
    if (application.editedSummary) {
      setContent(application.editedSummary);
    } else {
      setContent(autoGenerated);
    }
  }, [application.id, application.editedSummary, autoGenerated]);

  const handleSave = () => {
    if (isReadOnly) return;
    saveOperationsSummary(application.id, content);
    setIsSavedFeedback(true);
    setTimeout(() => setIsSavedFeedback(false), 2000);
  };

  const handleReset = () => {
    if (isReadOnly) return;
    resetOperationsSummary(application.id);
    setContent(autoGenerated);
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-200 dark:border-slate-800 pb-3">
        <div>
          <h3 className="text-sm font-bold text-slate-900 dark:text-white flex items-center space-x-2">
            <FileText className="w-4 h-4 text-indigo-500" />
            <span>Operations Intake Case Summary</span>
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Standardized plain-language summary for credit operations hand-off
          </p>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center space-x-2">
          {application.editedSummary && (
            <button
              disabled={isReadOnly}
              onClick={handleReset}
              className="flex items-center space-x-1.5 px-3 py-1.5 text-xs font-semibold text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-lg transition-colors disabled:opacity-50"
            >
              <RotateCcw className="w-3.5 h-3.5" />
              <span>Reset to Generated</span>
            </button>
          )}

          <button
            disabled={isReadOnly}
            onClick={handleSave}
            className={`flex items-center space-x-1.5 px-4 py-1.5 text-xs font-semibold rounded-lg shadow-sm transition-all disabled:opacity-50 ${
              isSavedFeedback
                ? 'bg-emerald-600 text-white'
                : 'bg-indigo-600 hover:bg-indigo-700 text-white'
            }`}
          >
            {isSavedFeedback ? (
              <>
                <Check className="w-3.5 h-3.5" />
                <span>Saved!</span>
              </>
            ) : (
              <>
                <Save className="w-3.5 h-3.5" />
                <span>Save Summary</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Edited marker banner if staff customized the summary */}
      {application.summaryEditedBy && (
        <div className="flex items-center space-x-2 px-3 py-2 bg-indigo-50 dark:bg-indigo-950/50 border border-indigo-200 dark:border-indigo-900/60 rounded-lg text-xs text-indigo-700 dark:text-indigo-300">
          <User className="w-3.5 h-3.5 shrink-0" />
          <span>
            Staff Customization: Edited by{' '}
            <strong className="font-semibold">{application.summaryEditedBy}</strong> on{' '}
            {formatDateTime(application.summaryEditedAt)}
          </span>
        </div>
      )}

      {/* Editor Textarea */}
      <div className="relative">
        <textarea
          rows={15}
          disabled={isReadOnly}
          value={content}
          onChange={(e) => setContent(e.target.value)}
          className="w-full p-4 text-xs font-mono rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-indigo-500 leading-relaxed disabled:opacity-80"
          placeholder="Operations summary..."
        />
      </div>

      <p className="text-[11px] text-slate-400">
        💡 Tip: The operations summary provides credit underwriters with an immediate snapshot of KYC readiness, income verification, and checklist completeness.
      </p>
    </div>
  );
};

  return null;
};
